url: "s3it4n.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/cookbook" # the subpath of your site, e.g. /blog
title: "Recetario"
description: "Libro de recetas de Instagram"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# GitHub Pages settings
github_username: s3it4n
repository: s3it4n/cookbook

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
